// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABxnP4d2wRFC6-7re8H_OCv2jLcmmNzb0',
    appId: '1:522424214900:web:0ec581a39b79c371123821',
    messagingSenderId: '522424214900',
    projectId: 'tripwise-app-9fa80',
    authDomain: 'tripwise-app-9fa80.firebaseapp.com',
    storageBucket: 'tripwise-app-9fa80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABxnP4d2wRFC6-7re8H_OCv2jLcmmNzb0',
    appId: '1:522424214900:android:816d5b67e9723aad123821',
    messagingSenderId: '522424214900',
    projectId: 'tripwise-app-9fa80',
    storageBucket: 'tripwise-app-9fa80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZFPtSB19R8-3ua7gbRlHRcb58mEsvNQ',
    appId: '1:522424214900:ios:d9e327429f2e7462123821',
    messagingSenderId: '522424214900',
    projectId: 'tripwise-app-9fa80',
    storageBucket: 'tripwise-app-9fa80.firebasestorage.app',
    iosClientId: '522424214900-rm8mmlilhcfk496i97s34l08fk78fm9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
