import datetime
from typing import Optional

class MarkdownExporter:
  def __init__(self, disclaimer: bool = True):
    self.include_disclaimer = disclaimer

  def export(self, response_text: str, filename: str = "ai_travel_plan.md") -> str:
    """
    Export travel plan to a well-formatted Markdown file.
    Includes metadata, disclaimer, and timestamp.
    Args:
      response_text (str): The agent's output (reasoning and summary).
      filename (str): The filename to save as.
    Returns:
      str: The path to the saved file.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    metadata = f"""# 🧳 AI Travel Itinerary\n\n**Generated:** {timestamp}\n"""
    disclaimer = "\n> **Disclaimer:** This itinerary is generated by AI and may not reflect real-time prices or availability. Always verify details before booking.\n" if self.include_disclaimer else ""
    content = f"{metadata}{disclaimer}\n---\n\n{response_text}\n"
    with open(filename, "w", encoding="utf-8") as f:
      f.write(content)
    return filename 